# Minimal configuration based on Antora Generator Template 
# Source: https://code.asam.net/common/templates/antora-base-repo-example/-/blob/standard_generator/site.yml
# tag::site[]
site:
  title: ASAM OpenMATERIAL
  url: https://asam-ev.github.io/OpenMATERIAL/
  start_page: asamopenmaterial:specification:index.adoc 
# end::site[]
urls: # Creates a redirect for the newest version to the link "latest"
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest

# tag::content[]
content:
  sources:
  - url: https://code.asam.net/common/asam-terminology.git
    start_path: .antora
    tags: [v*,V*]
  - url: .
    start_path: .antora
# end::content[]

ui:
  bundle:
    url: https://code.asam.net/common/antora-ui/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
#  supplemental_files: ./supplemental_ui # Activate this if you need to make local UI changes. Check the official Antora documentation for more information.

output:
  clean: true
  dir: ./build/site
  
runtime:
  fetch: true
